oi = imread('lena.jpeg');
niGuassian = imnoise(oi, 'gaussian', 0, 0.01);
s = 2;
h = fspecial('gaussian', [5 5], s);
fGaussian = imfilter(niGuassian, h);
mseG = immse(fGaussian, oi);
psnrG = psnr(fGaussian, oi);
mseNG = immse(niGuassian, oi);
psnrNG = psnr(niGuassian, oi);
nImageMedian = imnoise(oi, 'salt & pepper', 0.02);
fMedian = medfilt2(rgb2gray(nImageMedian), [3 3]);
mseM = immse(fMedian, rgb2gray(oi));
psnrM = psnr(fMedian, rgb2gray(oi));
mseNoisyM = immse(rgb2gray(nImageMedian), rgb2gray(oi));
psnrNoisyM = psnr(rgb2gray(nImageMedian), rgb2gray(oi));

figure;
subplot(1, 3, 1);
imshow(oi);
title({'Original Image', sprintf('MSE: %.4f', 0), 'PSNR: Inf dB'});
subplot(1, 3, 2);
imshow(nImageMedian);
title({'Noisy Image (Salt & Pepper)', sprintf('MSE: %.4f', mseNoisyM), sprintf('PSNR: %.2f dB', psnrNoisyM)});
subplot(1, 3, 3);
imshow(fMedian);
title({'Filtered (Median)', sprintf('MSE: %.4f', mseM), sprintf('PSNR: %.2f dB', psnrM)});
figure;
subplot(1, 3, 1);
imshow(oi);
title({'Original Image', sprintf('MSE: %.4f', 0), 'PSNR: Inf dB'});
subplot(1, 3, 2);
imshow(niGuassian);
title({'Noisy Image (Gaussian Noise)', sprintf('MSE: %.4f', mseNG), sprintf('PSNR: %.2f dB', psnrNG)});
subplot(1, 3, 3);
imshow(fGaussian);
title({'Filtered (Gaussian)', sprintf('MSE: %.4f', mseG), sprintf('PSNR: %.2f dB', psnrG)});
